### ISSUE TITLE
Compiling for Android (aarch64)

### ISSUE THREAD

**Issue by redwhite197** [frida/frida-go#11]
1. Downloaded NDK
2. Move frida.h / frida.a files to toolchain include /lib dirs.

export CGO_ENABLED=1
export GOOS=android
export GOARCH=arm64
export CC=.../android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang
go build test.go

Error while compiling:

`# github.com/frida/frida-go/frida
ld: error: unable to find library -lrt
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by NSEcho** [comment]
Hi, can you try removing `-lrt` from this line inside `frida/frida.go` file https://github.com/frida/frida-go/blob/ac54cbc9f77c2b87b3b9ff0b69e604cee596a42a/frida/frida.go#L14 

And if it is working, let me know so I can test it more and push the change.

Edit: are you cross compiling

**Comment by redwhite197** [comment]
> Hi, can you try removing `-lrt` from this line inside `frida/frida.go` file
> 
> https://github.com/frida/frida-go/blob/ac54cbc9f77c2b87b3b9ff0b69e604cee596a42a/frida/frida.go#L14
> 
> And if it is working, let me know so I can test it more and push the change.

yeah. it's works. Ty <3
