### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by bmteller** [frida/frida-go#12]
I noticed in the Swift bindings a lot of the Frida methods are called with `Runtime.scheduleOnFridaThread`. I assume this is because there are potential thread safety issues with Frida objects being modified by Frida on the Frida thread and Swift code trying to modify those same objects from different threads using the Frida methods. Is it possible for the same issues to happen with the golang bindings?

**Comment by NSEcho** [comment]
Hi, in golang bindings, are the calls are directly called using frida-core API which means they are essentially scheduled on frida thread so there is no need for `scheduleOnFridaThread` inside the go bindings. Another thing which could mess things around but is implemented correctly that the callbacks are called inside the goroutines to prevent the locking frida thread. Hope that this is the answer you were looking for.

**Comment by bmteller** [comment]
thanks for the explanation. so the swift bindings seem to need it because they call the  asynchronous  methods to perform the operations but the go bindings don't because they use the `_sync` methods which schedule stuff on the main thread themselves.

**Comment by NSEcho** [comment]
Yeah, long term goal is to move golang api to async one
