### ISSUE TITLE
unable to find libray -lrt

### ISSUE THREAD

**Issue by luckyflyhorse** [frida/frida-go#20]
![image](https://github.com/frida/frida-go/assets/21310318/c08f55d5-b0c4-4725-9062-f187087153a4)

maybe can delete the rt of LDFLAGS in frida.go

![image](https://github.com/frida/frida-go/assets/21310318/4ccda94b-4862-4bda-a3ba-6b260ffd6c6b)

there is no librt.a/librt.so in NDK

**Comment by NSEcho** [comment]
Hi there, thank you for bringing this up, I will push the fix today

**Comment by NSEcho** [comment]
@luckyflyhorse I have pushed [v0.6.10](https://github.com/frida/frida-go/releases/tag/v0.6.10), let me know if it is working okay now.
