### ISSUE TITLE
Unable to attach to session when frida tools can.

### ISSUE THREAD

**Issue by dylanhitt** [frida/frida-go#21]
Hello,

When my process spins up it is able to perform the following code snippet just fine. After a few hours I begin receiving the error `FError: Device is gone` from the `.Attach` 

```go
func (d *IOSDevice) hasFrida() (error, bool) {
	fridaDevice, err := frida.DeviceById(d.config.Serial)
	if err != nil {
		return err, false
	}
	d.log.Infof("found frida device %s", fridaDevice.ID())
	session, err := fridaDevice.Attach(0, nil)
	if err != nil {
		return err, false
	}
	session.Detach()
	return nil, true
}
```

The `d.log.Infof("found frida device %s", fridaDevice.ID())` line shows:

```log
{"device":"id","level":"info","msg":"found frida device my-id","time":"2023-10-03T16:00:21Z","type":"Metal"}
```

The error returned from `.Attach` is: `FError: Device is gone`

If I jump into the container running this and install frida tools I can successfully:

```
# frida -U -p 0
     ____
    / _  |   Frida 16.1.4 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to iOS Device (id=81ff2e346b285f37294baf60ba8f72df7a121aab)
                                                                                
[iOS Device::SystemSession ]->
```
As shown my frida version is 16.1.4 both the the cli and the devkit I'm using. My frida-go version is `[github.com/frida/frida-go](http://github.com/frida/frida-go) v0.6.10`. The only way I've found to fix the go process is to reboot the container. Restarting the device and re jailbreaking with a fresh frida installation doesn't seem to work either.

I'm not sure if the memory leak is an issue, but below are my current thoughts on debugging this:

I started to look into the file descriptors of the running process and began to see way more than expected, so it could be on me.

I have yet to isolate this further as I'm away from my setup and I will provide more detail once I get there.

I have also since changed my code to following 

```go
func (d *IOSDevice) initFridaDevice() error {
	fridaDevice, err := frida.DeviceById(d.config.Serial)
	if err != nil {
		return err
	}
	d.log.Infof("found frida device %s", fridaDevice.ID())
	d.fridaDevice = fridaDevice
	return nil
}

func (d *IOSDevice) hasFrida() (error, bool) {
	if d.fridaDevice == nil {
		err := d.initFridaDevice()
		if err != nil {
			return err, false
		}
	}
	if d.fridaDevice.IsLost() {
		err := d.initFridaDevice()
		if err != nil {
			return err, false
		}
	}
	session, err := d.fridaDevice.Attach(0, nil)
	if err != nil {
		return err, false
	}
	session.Detach()
	return nil, true
}
```

Thinking that maybe I was instantiating many devices, but the issue still persists.

**Comment by dylanhitt** [comment]
Little update on this: fixed my memory leak it was something else. 

However this still seems to be an issue. I experience this with both android and ios devices.

**Comment by NSEcho** [comment]
Hi @dylanhitt, thank you for your detailed report. Can you tell me is the time of running on both frida-go and standard CLI tools the same and what amount is it, so that I can try to recreate it

**Comment by dylanhitt** [comment]
So the frida-go process runs about every ~10 minutes (and on some changes it will re run), but I can force it to go whenever (and I have). When I notice a device reaches this state, I jump into the running container and install frida-tools and every time attaching works meanwhile the go process is reporting the `FError: Device is gone`. 

Yesterday I added the same frida go process to my android devices and the issue is much more prevalent with those devices.  

My current code looks like this. Once I get back to my stand alone devices I can spin up the same tests to see if I can recreate it in isolation. My initial thoughts was that I have something taking over the usb bus, but I don't believe that's the case since `FindDeviceByID()` always works.

```go
func (d *BaseDevice) hasFrida() (error, bool) {
	fridaDevice, err := frida.DeviceById(d.config.Serial)
	if err != nil {
		return err, false
	}
	d.log.Infof("found frida device %s", fridaDevice.ID())
	session, err := fridaDevice.Attach(0, nil)
	if err != nil {
		return err, false
	}
	d.log.Info("successfully attached to frida device")
	session.Detach()
	session.Clean()
	return nil, true
}
```

**Comment by NSEcho** [comment]
Can you try to refactor your code to use strictly `NewDeviceManager` followed by `EnumerateDevices` and use `FindDeviceByID` to get that device

**Comment by dylanhitt** [comment]
Sure thing

**Comment by dylanhitt** [comment]
So you're essentially asking for this:

```golang
func NewBaseDevice(config *common.DeviceAgentConfig, exec *Executor) BaseDevice {
        # some other code here
	return BaseDevice{
		Executor:  exec,
		deviceMgr: frida.NewDeviceManager(),
		config:    config,
		log:       log,
	}
}

func (d *BaseDevice) hasFrida() (error, bool) {
	devices, err := d.deviceMgr.EnumerateDevices()
	if err != nil {
		return err, false
	}
	d.log.Infof("frida found %s", len(devices))
	fridaDevice, err := d.deviceMgr.FindDeviceByID(d.config.Serial)
	if err != nil {
		return err, false
	}
	d.log.Infof("found frida device %s", fridaDevice.ID())
	session, err := fridaDevice.Attach(0, nil)
	if err != nil {
		return err, false
	}
	d.log.Info("successfully attached to frida device")
	session.Detach()
	session.Clean()
	return nil, true
}
```

**Comment by NSEcho** [comment]
Yes, let me know how that one goes

**Comment by dylanhitt** [comment]
Haven't seen it since I switched over yesterday. I'm only running this on IOS devices for right now. I'll update once I move this to all my devices. 

Thank you

**Comment by NSEcho** [comment]
Excellent, looking forward to the feedback, just don't forget to clean up the resources

**Comment by dylanhitt** [comment]
I assume `just don't forget to clean up the resources` you're referring to me not cleaning the `fridaDevice`?

**Comment by NSEcho** [comment]
You can keep the reference to the manager, but cleanup the resources inside of function if they are one-shot

**Comment by NSEcho** [comment]
Hey @dylanhitt, can we close the issue now

**Comment by dylanhitt** [comment]
Yes, switching to the manager pretty much solved my problem. 

Thank you
