### ISSUE TITLE
v0.7.1 fails to compile on Debian with `cc`

### ISSUE THREAD

**Issue by adamshugar** [frida/frida-go#34]
When running `go build` with v0.7.1 as a dependency, I get:
```
cc1: error: '-Wno-error=incompatible-function-pointer-types': no option '-Wincompatible-function-pointer-types'; did you mean '-Wincompatible-pointer-types'?
```

Running `cc --version` gives:
```
cc (Debian 12.2.0-14) 12.2.0
```

Reverting to v0.7.0 fixes the problem. I suspect it's related to this issue: https://github.com/frida/frida-go/issues/30

Let me know if more information would be helpful; I think it's a quick fix with compiler flag names.

**Comment by dylanhitt** [comment]
This is fixed on main. I believe we just need to cut a tag.

**Comment by dylanhitt** [comment]
#33 here

**Comment by NSEcho** [comment]
Hey there, the linux does not require that flag so I think it should be removed. I can push commit in a couple of hours

**Comment by dylanhitt** [comment]
@NSEcho it's already fixed with #33 a new release just needs to be created.

**Comment by NSEcho** [comment]
You are right, thanks, will release it now

**Comment by NSEcho** [comment]
@adamshugar everything okay now?
