### ISSUE TITLE
could not determine kind of name for C.frida_script_enable_debugger_sync

### ISSUE THREAD

**Issue by youfak** [frida/frida-go#35]
../gowork/pkg/mod/github.com/frida/frida-go@v0.7.2/frida/script.go:97:2: could not determine kind of name for C.frida_script_disable_debugger_sync
../gowork/pkg/mod/github.com/frida/frida-go@v0.7.2/frida/script.go:86:2: could not determine kind of name for C.frida_script_enable_debugger_sync

**Comment by magaldima** [comment]
I'm seeing a similar issue: `could not determine kind of name for C.frida_device_open_service_sync`

**Comment by NSEcho** [comment]
What version of frida devkit you have on your system installed?

**Comment by NSEcho** [comment]
@magaldima `frida_device_open_service_sync` is available starting from Frida 16.3.0 so make sure that your Frida devkit version is atleast 16.3.0

**Comment by magaldima** [comment]
Just upgraded to frida 16.3.3 and now I'm seeing this issue:

```
# github.com/frida/frida-go/frida
../../../../go/pkg/mod/github.com/frida/frida-go@v0.10.1/frida/variants_to_go.go:56:13: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gsize *' (aka 'unsigned long *') [-Wint-conversion]
                                                                           (gsize)n_elements,
                                                                           ^~~~~~~~~~~~~~~~~
/usr/local/include/frida-core.h:13833:96: note: passing argument to parameter 'n_elements' here
                                                                         gsize                *n_elements,
```

Note, I'm using the latest go-frida version: `require github.com/frida/frida-go v0.10.1`.

I've also copied the `frida-core.h` and `libfrida-core.a` files from the Frida Core Devkit 16.3.3 for MacOS arm64 to their respective directories according to the README installation instructions.

**Comment by magaldima** [comment]
I believe this could have something to do with #30 and the xcode version installed. I have `xcode-select version 2408.`
