### ISSUE TITLE
Error building with v0.10.1

### ISSUE THREAD

**Issue by blacktop** [frida/frida-go#38]
../../../../go/pkg/mod/github.com/frida/frida-go@v0.10.1/frida/variants_to_go.go:56:13: error: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gsize *' (aka 'unsigned long *') [-Wint-conversion]
                                                                           (gsize)n_elements,
                                                                           ^~~~~~~~~~~~~~~~~
/usr/local/homebrew/include/frida-core.h:13834:96: note: passing argument to parameter 'n_elements' here
                                                                         gsize                *n_elements,
                                                                                               ^
1 error generated.

**Comment by NSEcho** [comment]
Can you try it with `v0.10.2`, I believe this should be fixed.

**Comment by blacktop** [comment]
../../../../go/pkg/mod/github.com/frida/frida-go@v0.10.2/frida/device.go:614:10: could not determine kind of name for C.frida_device_open_service_sync

**Comment by NSEcho** [comment]
That to me seems like you don't have devkit for frida core `16.3.x`.

**Comment by blacktop** [comment]
K, let me reinstall 16.3 and try again

**Comment by blacktop** [comment]
We're good! Thanks ❤️
