### ISSUE TITLE
[QUESTION] fatal error: 'frida-core.h' file not found

### ISSUE THREAD

**Issue by cleverhu** [frida/frida-go#4]
**Please describe your feature request below in few sentences.**
When I run the below code , it reported `vendor/github.com/frida/frida-go/frida/application.go:3:10: fatal error: 'frida-core.h' file not found`, how can I resolve it? Thanks.
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/51436614/205444017-d43d9501-3683-47cd-a167-e67f46eda9ce.png">

**Potential usage you would like to see**
Small example of potential API usage.
```
package main

import (
	"bufio"
	"fmt"
	"os"

	"github.com/frida/frida-go/frida"
)

var script = `
Interceptor.attach(Module.getExportByName(null, 'open'), {
	onEnter(args) {
		const what = args[0].readUtf8String();
		console.log("[*] open(" + what + ")");
	}
});
Interceptor.attach(Module.getExportByName(null, 'close'), {
	onEnter(args) {
		console.log("close called");
	}
});
`

func main() {
	mgr := frida.NewDeviceManager()

	devices, err := mgr.EnumerateDevices()
	if err != nil {
		panic(err)
	}

	for _, d := range devices {
		fmt.Println("[*] Found device with id:", d.ID())
	}

	localDev, err := mgr.LocalDevice()
	if err != nil {
		fmt.Println("Could not get local device: ", err)
		// Let's exit here because there is no point to do anything with nonexistent device
		os.Exit(1)
	}

	fmt.Println("[*] Chosen device: ", localDev.Name())

	fmt.Println("[*] Attaching to Telegram")
	session, err := localDev.Attach("Telegram", nil)

	script, err := session.CreateScript(script)
	if err != nil {
		fmt.Println("Error ocurred creating script:", err)
	}

	script.On("message", func(msg string) {
		fmt.Println("[*] Received", msg)
	})

	if err := script.Load(); err != nil {
		fmt.Println("Error loading script:", err)
		os.Exit(1)
	}

	r := bufio.NewReader(os.Stdin)
	r.ReadLine()
}

```

**Comment by NSEcho** [comment]
Hi, what is your go version and did you install frida-core devkit files(libfrida-core.a) and frida-core.h

**Comment by cleverhu** [comment]
> Hi, what is your go version and did you install frida-core devkit files(libfrida-core.a) and frida-core.h

Thanks for reply.
My go version is `go version go1.19 darwin/arm64`.
I don't know how to install `frida-core devkit files(libfrida-core.a) and frida-core.h`.
I just install python3 and pip3 and excute `pip3 install frida frida-tools`.

**Comment by NSEcho** [comment]
So you want to go to the [releases](https://github.com/frida/frida/releases) and download the archive for your OS and architecture. For example frida-core-devkit-macos-x86_64.tar.xz. 

You download the archive, extract it and copy libfrida-core.a to /usr/local/lib and frida-core.h inside /usr/local/include and then you should be able to build frida-go

**Comment by cleverhu** [comment]
> So you want to go to the [releases](https://github.com/frida/frida/releases) and download the archive for your OS and architecture. For example frida-core-devkit-macos-x86_64.tar.xz. 
> 
> You download the archive, extract it and copy libfrida-core.a to /usr/local/lib and frida-core.h inside /usr/local/include and then you should be able to build frida-go

Thank you very much, I will try it right away.

**Comment by cleverhu** [comment]
Thanks again, it works perfectly in my local.

**Comment by rew1nter** [comment]
Just came across this same issue. 
Can't this be automated within the package?

**Comment by NSEcho** [comment]
I don't see how this could be automated inside the package. One of the solutions would be some kind of shell script that would be run prior to building the binary. 

Feel free to PR it if would like to work on it. 

Ideally, it should receive the following arguments:

* os (linux, macos or android)
* arch
* include location
* lib location

**Comment by hameedhub** [comment]
@NSEcho  this issue is still present on `github.com/frida/frida-go v1.0.2` go version `go 1.25.7` 

> ../../go/pkg/mod/github.com/frida/frida-go@v1.0.2/frida/session_options.go:3:10: fatal error: 'frida-core.h' file not found
>     3 | #include <frida-core.h>
>       |          ^~~~~~~~~~~~~~
> 1 error generated.

I have not tried the work around yet, I will do so shortly, and also I could take a look and raise a PR for the issue.

**Comment by NSEcho** [comment]
@hameedhub you need to follow steps here https://github.com/frida/frida-go/issues/4#issuecomment-1338983538

It is not workaround, it is expected as can be read inside README of this repo.
