### ISSUE TITLE
Build Failure of frida-go When Cross-Compiling to Linux

### ISSUE THREAD

**Issue by laterinc** [frida/frida-go#40]
I encountered a build failure when trying to cross-compile the frida-go library from macOS to Linux. The following errors occur during the build process:
```
../frida.go:21:25: undefined: frida.DeviceInt
../frida.go:49:21: undefined: frida.NewDeviceManager
../frida.go:50:46: undefined: frida.DeviceTypeUsb
../frida.go:64:57: too many errors
```

Here are relevant sections of the code that are causing the issue:
```
import (
	"fmt"
	"github.com/frida/frida-go/frida"
)
func GetDevice() (*frida.DeviceInt, error) {
       manager := frida.NewDeviceManager()
       device, err := manager.DeviceByType(frida.DeviceTypeUsb)
       if err != nil {
		return nil, fmt.Errorf("could not get USB device: %v", err)
       }
       return &device, nil
}
```
Environment:
	•	frida-go Version: v0.10.3
	•	Go Version: 1.23.1
	•	Operating System: macOS (using cross-compilation settings GOARCH=amd64)

Steps to Reproduce:
	1.	Run the build command: GOOS=linux GOARCH=amd64 go build -o test cmd/main.go
	2.	Observe the build errors that occur.

Attempts to Resolve:
	•	Ensured that the frida-go version is correct.
	•	Cleared Go cache and re-downloaded dependencies.

Please take a look at this issue and provide assistance. Thank you!

**Comment by NSEcho** [comment]
I did not plan to support cross-compilation but as a workaround you can use docker containers and build it that way.
