### ISSUE TITLE
[FEATURE] smaller binaries

### ISSUE THREAD

**Issue by blacktop** [frida/frida-go#6]
This is pretty awesome and thank you for your hard work!

I just tried it out, however, the statically linked binary I made was ... 80MBs!  Not that big of an issue in the modern age of massive storage, but was just wondering if there was any way to shrink that down? 

Thanks again!

**Comment by NSEcho** [comment]
Hi and thank you. I guess not much can be done because using the `cgo` will generally produce larger binaries. Passing `-ldflags="-s -w"` to the `go build` can reduce the binary. For the example below, it got from 56MB down to 46MB.

```golang
package main

import (
	"fmt"

	"github.com/frida/frida-go/frida"
)

func main() {
	manager := frida.NewDeviceManager()
	devices, err := manager.EnumerateDevices()
	if err != nil {
		panic(err)
	}

	fmt.Printf("[*] Frida version: %s\n", frida.Version())
	fmt.Println("[*] Devices: ")
	for _, device := range devices {
		fmt.Printf("[*] Params for: %s (%s)\n", device.Name(), device.ID())
		if device.ID() != "socket" {
			params, err := device.Params()
			if err != nil {
				panic(err)
			}
			for k, v := range params {
				fmt.Printf("\t%s => %v\n", k, v)
			}
		}
	}
}
```

**Comment by blacktop** [comment]
Right on! Ya I'm already using those flags.  My "compromise" is I'm building release artifacts that have the **frida** functionality so if someone wants to use it they can grab the bigger binaries.

Thanks again!

**Comment by NSEcho** [comment]
I would like to reopen this and point to the [https://frida.re/docs/footprint/](https://frida.re/docs/footprint/). Configuring options inside the `config.mk` will reduce the size of the library, therefore the end built go binary.
